### ISSUE TITLE
porting to new garden structure + putting on PyPi

### ISSUE THREAD

**Issue by goffi-contrib** [kivy-garden/garden.contextmenu#11]
Hello,

I there still somebody maintaining this widget? I would like to port it to new garden structure and put it on PyPi, but I'm not the original author or maintainer so I'm asking here first.

Thanks!

**Comment by AndreMiras** [comment]
Thanks! You're now a collaborator of the freshly created https://github.com/kivy-garden/contextmenu
You can follow the guide to port it to the new structure https://kivy-garden.github.io/#guideformigratingflowersfromlegacystructure

**Comment by martinsik** [comment]
@AndreMiras Hey, I'm sorry but I'm not able to maintain this library any more. I had to shift to other technologies over the past 3 years so I'm not even using Kivy myself for hobby projects any more.

**Comment by AndreMiras** [comment]
No worries we'll take over with the help of contributors.
Thanks for what you did for the community :hearts:  have a good one :beers:

**Comment by goffi-contrib** [comment]
hello @martinsik thanks for your work. No worries we'll take care of porting it to new structure.

**Comment by goffi-contrib** [comment]
@AndreMiras I've just pushed the converted flower. As for `modernmenu` could you:
- check that I did it fine
- add to coveralls
- upload to pypi

? Thanks :)

Meanwhile, I'm doing a PR to update this README to redirect to the new repo, so the old one can be archived.

**Comment by AndreMiras** [comment]
1) check that I did it fine

That seems fine, however I couldn't really run the context menu locally directly.
I've tried `python kivy_garden/contextmenu/context_menu.py` which opens and closes the app quickly. And `python kivy_garden/contextmenu/__init__.py` which is failing with `ModuleNotFoundError: No module named '__main__.context_menu'; '__main__' is not a package`

2) add to coveralls

Done and rebuilt, CI is green now.

3) upload to pypi

Done too via:
```sh
python setup.py sdist bdist_wheel
twine check dist/*
twine upload dist/*
```
Available in https://pypi.org/project/kivy-garden-contextmenu/ and your are collaborator for subsequent releases.

**Comment by goffi-contrib** [comment]
@AndreMiras for 1. there is an `examples` directory, after installing the menu you should be able to run all of them.
Thanks again for your quick feedback and actions.
Should I close this issue of wait for 1. to be checked? I did try `examples` myself and they run fine for me.

**Comment by AndreMiras** [comment]
I confirm it works with:
```
PYTHONPATH=. venv/bin/python examples/simple_app_menu.py
```
Yes we should close and follow up any conversation on the new repo if needed https://github.com/kivy-garden/contextmenu
Thanks again
